version: '3.8'

services:
  client:
    container_name: "app-client"
    build: .
    env_file:
      - ./.env
    ports:
      - "80:80"
    networks:
      - default
networks:
  default: